name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
            submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: build
        run: |
          yarn
          yarn build
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub pages
        id: deploy
        uses: actions/deploy-pages@v2
